### ISSUE TITLE
Bug in utils.py

### ISSUE THREAD

**Issue by breisfeld** [USEPA/ctx-python#1]
Hi, I believe that there is an extra line in the `read_env` function in `utils.py` that is causing a problem when reading the `.env` file. 

This extra line is ultimately causing the `x-api-key` not to be found. 

The line in questions is

```
    config = {"-".join(k.lower().split("_")[2:]):v for k,v in config.items()}
```

**Comment by kaphillips** [comment]
Just pushed new version that should fix this problem.
